name: Demo using HTML Code

on:
  push:
    banches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: List files
       run: ls 
       
     - name: Print HTML file
       run: cat index.html
       
     - name: Upload to Gitbub pages
       uses: actions/upload-pages-artifact@v3
       with:
         path: ./

     - name: Publish
       uses: actions/deploy-pages@v4
